### ISSUE TITLE
Domain local groups missing

### ISSUE THREAD

**Issue by Naihan** [SteveSyfuhs/Kerberos.NET#152]
Sorry if it was already discussed.
Trying out the library and I'm noticing that only domain global groups are extracted from the PAC certificate. If the user is a member of a domain local group i dont see the group sid in the claims, am i missing somthing?

**Comment by SteveSyfuhs** [comment]
Thanks for catching this. Those groups are included in a separate property of the PAC, which weren't getting added to the claims list. You can verify this by checking the identity:

```csharp
var result = await authenticator.Authenticate(ticket) as KerberosIdentity;

var pac = result.Restrictions[AuthorizationDataType.AdWin2kPac].First() as PrivilegedAttributeCertificate;

var resourceGroups = pac.LogonInfo.ResourceGroups;
var extra = pac.LogonInfo.ExtraSids;
```

I've since fixed this in this #153 and a nuget package will be pushed once the build and tests pass.

**Comment by SteveSyfuhs** [comment]
Nuget is updated to 4.0.8 https://www.nuget.org/packages/Kerberos.NET/4.0.8

**Comment by Naihan** [comment]
@SteveSyfuhs thanks so much!

**Comment by Naihan** [comment]
@SteveSyfuhs in order to get the group name for a domain local group do i have to use LDAP or is there a better way?

**Comment by SteveSyfuhs** [comment]
On Windows you'd call [`LsaLookupSids`](https://docs.microsoft.com/en-us/windows/win32/api/ntsecapi/nf-ntsecapi-lsalookupsids) which would try and find a domain controller and ask it to translate. Assuming that's not possible because its not running Windows, you don't have line of sight to a DC, or you're not domain joined, then yes you have to make an LDAP call. That LDAP call would be something like

```
"(ObjectSID=S-1-5-21-111111111-222222222-333333333-4444444444)"
```
