### ISSUE TITLE
Add support for RFC 8009 (SHA256 and SHA384)

### ISSUE THREAD

**Issue by SteveSyfuhs** [SteveSyfuhs/Kerberos.NET#159]
**Is your feature request related to a problem? Please describe.**
SHA-1 is considered deprecated and shouldn't actively be used. Kerberos recently added support for SHA256 through RFC 8009.

**Describe the solution you'd like**
Implement an abstract `Rfc8009Transformer` class that inherits from `AESTransformer`. Implement `AES128SHA256Transformer` and `AES256SHA284Transformer` that provide the specific algorithm.

**Describe alternatives you've considered**
None.

**Additional context**
There aren't many active implementations of SHA256 _in use_ in the wild so verifying interop and compatibility will be tricky. Should consider how to test this.

**Comment by SteveSyfuhs** [comment]
We have an internal build of this working and will publish in the near future.

**Comment by marcelhintermann** [comment]
Hi @SteveSyfuhs 

Do you have any update on this topic?

Thanks and best regards,
Marcel

**Comment by SteveSyfuhs** [comment]
I have a private branch with the changes. It's still undergoing an internal review. Is this something of specific interest?

**Comment by marcelhintermann** [comment]
> I have a private branch with the changes. It's still undergoing an internal review. Is this something of specific interest?

I don't know if my problem is related with this issue here. I've used Kerberos.net for an authentication middleware in a .net core application. When a keytab file is loaded with **only** the `AES256-SHA1` cipher it's not working. All the other ciphers work fine.

**Comment by SteveSyfuhs** [comment]
Active Directory doesn't support SHA256/384.

The usual cause for AES to not work is because the salt doesn't match what the KDC expects it to be so the derived key is wrong.

How are you generating the keytab?

**Comment by marcelhintermann** [comment]
Okay, didn't know that - thanks for the explanation.

I generated the keytab as follow:
`ktpass.exe -out service-net.keytab -princ service-net@AD -mapUser service-net@AD -pass xxx -crypto AES256-SHA1 -ptype KRB5_NT_PRINCIPAL -princ HTTP/service-net.domain.com@AD`

**Comment by SteveSyfuhs** [comment]
For completeness try `-ptype KRB5_NT_SRV_HST`. Also, what error are you getting from kerb.net?

**Comment by marcelhintermann** [comment]
I've got it to work and I can confirm that Kerberos.net works totally fine with keytabs with all provided ciphers.
Of course it was again me, who configured something wrong. The `msDS-SupportedEncryptionTypes` flag was configured wrong, so that `AES256_CTS_HMAC_SHA1_96` was not enabled for the account :see_no_evil:

Got the following error:
`System.InvalidOperationException: Key EType AES128_CTS_HMAC_SHA1_96 must match the encrypted data EType AES256_CTS_HMAC_SHA1_96`

Many thanks for your help! And even more thanks for building such a great library!!!
I've learned a lot because of it...
