### ISSUE TITLE
InvalidOperationError on Authenticate

### ISSUE THREAD

**Issue by NidG** [SteveSyfuhs/Kerberos.NET#162]
Hey ,
When calling the kerberosClinet.Authenticate() , am getting the InvalidOperationError - "Connection pool maxed out at 11 connections " . Could I get some help regarding possible scenarios which can make this issue crop up and any possible solution ?

**Comment by SteveSyfuhs** [comment]
This happens when a client attempts to connect to more than 10 unique KDCs within a 30 second window. The client will pool all outbound connections based on target address, so one client to 11 KDCs will throw an error. The client is intended to be a on per-user basis and it will stick to whichever KDC it succeeded against first for a period of time or until it fails in the future, so it's unusual for the client to successfully connect to multiple servers in such a short period of time. I suppose if you're trying to open connections in parallel you could hit the maximum after all the pools are filled up, though that's not recommended.

Can you describe what you're trying to do here?

Also, there was this bug recently https://github.com/dotnet/Kerberos.NET/pull/158. It was fixed and there's an updated nuget package too.

Worst case you can bump up the max pool size:

```csharp
var tcp = client.Transports.OfType<TcpKerberosTransport>().FirstOrDefault();
tcp.MaxPoolSize = 200;
```

**Comment by NidG** [comment]
Thank you Steve.
What I am trying to do is - from a .Net Core 3.1 application , I need to call a web api and pass a kerberos token to it. Currently , for every webapi call , am calling kerberosClinet.Authenticate() and then kerberosClient.GetServiceTicket() . The frequency of calling the web api is high. It can be upto 20-30 time in a minute. So , after some time of execution , I start getting the error which I have mentioned above.

**Comment by SteveSyfuhs** [comment]
I would recommend reusing the client if you can. It's intended to be used on a 1:1 basis per client credential.

Otherwise I would recommend increasing the MaxPoolSize to something larger and see if that resolves it. It sounds like you're genuinely making lots of connections concurrently which can't be pooled.

**Comment by NidG** [comment]
Hey Steve ,
I did resuse the client this time. But , the next error came up after approx 10-12 hrs . It said that "Cannot request a service ticket until a user is authenticated" . I am assuming that it means the client authorization has expired. Is there any way we can verify if the authorization is active or expired before calling the kerberosClient.GetServiceTicket() ?

**Comment by SteveSyfuhs** [comment]
You might try enabling ticket renewal.

client.RenewTickets = true;

That will keep tickets alive for about 14 days, at which point you must force a reauth.

________________________________
