### ISSUE TITLE
When to re-authenticate

### ISSUE THREAD

**Issue by BrianBroe** [SteveSyfuhs/Kerberos.NET#212]
I use the KeberosClient in a web service to get a token for another web request.
The KeberosClient is long living, so I don't do a login every time since the tokens can be used for 10 hours and renewed for 24 hours.
Is there any way to see if I need to authenticate again? I thought I could get the expiration or the "renew until" of the TGT from the Cache, but that does not seem to be exposed?

**Comment by SteveSyfuhs** [comment]
There's a few options. 

The first is to enable automatic ticket renewal `kerbClient.RenewTickets = true`. The way this works is a background task is kicked off for each client that wakes up every `RefreshPollInterval` (every 30 sec) and if the the TGT expires in `<= RenewTicketsThreshold` (15 min) it'll attempt to renew the ticket up until the ticket is no longer renewable. In a standard AD environment this is 7 days.

The second is to wait for the `GetServiceTicket` call to fail with a specific exception `InvalidOperationException("Cannot request a service ticket until a user is authenticated")`. This occurs when the TGT can't be used anymore because its expired or just not present.

The third option is to derive your own cache from the existing `MemoryTicketCache` or `Krb5TicketCache` and peak into the contents yourself.

**Comment by BrianBroe** [comment]
Thanks for the answers.
Is there a reason why the expiration and renewal period is hidden? Seems to be useful information..
If I were to make my own cache, how would I use that instead of the existing?

**Comment by SteveSyfuhs** [comment]
No particular reason/didn't think of a use case that warranted it at the time.

It would likely be a fairly trivial addition if you're interested in making a PR to add it.

Otherwise to make a custom cache I'd recommend inheriting from MemoryTicketCache or Krb5TicketCache if you want it to go to file.

class MyCache : MemoryTicketCache {}

vat client = new KerberosClient() { Cache = new MyCache()};

________________________________

**Comment by BrianBroe** [comment]
MemoryTicketCache is internal sealed?

**Comment by SteveSyfuhs** [comment]
Ah, that would be problematic then, sorry. Bad advice. 🙂

You could implement your own `MemoryTicketCache` class. It's somewhat trivial. It's really just a `ConcurrentDictionary<string, CacheEntry>` under the covers. Just copy and paste from here and extend as you need to.

Alternatively you can also peek into the underlying message. That too will contain the expiration. It would require decrypting the message, but the key is right beside it.

**Comment by BrianBroe** [comment]
I think I'll go with the exception approach. :)
Thanks for the help.
