### ISSUE TITLE
Invalid TKT/TGS Encyrption Type

### ISSUE THREAD

**Issue by Julien042** [SteveSyfuhs/Kerberos.NET#219]
Hi Steve,

When I am instantiating a new Krb5Config object using my company's /etc/krb5_conf file, I am getting this exception : 
- Requested value 'des3_hmac_sha1' was not found

I believe my firm is using an encryption type that is not declared in the EncryptionType enum of Kerberos.NET.

Is there something I can do on my end to help with this?

Thank you

**Comment by SteveSyfuhs** [comment]
You are correct, that isn't a value we support. We don't support the DES or 3DES crypto systems, but we do try and at least parse the values. In this case des-hmac-sha1 and des3-hmac-sha1 are just missing from the ETypes enum list.

There are three options here:

1. Remove des3-hmac-sha1 from your config. This is frankly the best course of action because DES and 3DES are deprecated and potentially dangerous. This is not a breaking change if you're not using DES or 3DES. This could be a breaking change if you are, but again, fairly dangerous so its wise to plan to move away from it anyway.
2. Open a PR that adds the etypes to the EncryptionType enum
3. Open a PR that adds an alias from the two etypes to something benign like des_cbc_sha1
4. Or (2) and (3)

If you do go down the PR route I can approve fairly quickly and push an updated Nuget package. Alternatively I can do the work, but it'll take a bit to schedule the work.

**Comment by Julien042** [comment]
Thank you, I'll go with 1. and will give a try to 4. as well.

I do have one question though. Assuming you work for a large organization that uses a single (read-only) krb5_conf file that you are consuming with Kerberos.NET. Do you think there's a risk that a new encryption type is added to that file without sufficient notice and that new entry is yet to be supported by the Kerberos.NET library, then the Krb5Config instantiation would fail subsequently. Shall we consider implementing a fail-safe when that happens so that we always revert to a benign encryption type in case of a missing type in the enum?

**Comment by SteveSyfuhs** [comment]
That's a reasonable approach here. Thanks for being willing to take it on. Handling unknown values is definitely a good idea. That was the original attempt here, but in retrospect etypes and such things don't necessarily have to abide by the registry.

The more I think about it though, the only benign etype would actually be to not return one at all, otherwise it'd be somewhat unpredictable which could potentially be dangerous (generically). For collections it would just not be present in the list, and for single values it would return 0. This should be fairly straightforward to implement, basically whereever an enum is parsed it should just be ignored on null or parse exception.

________________________________

**Comment by SteveSyfuhs** [comment]
This has been fixed. It ignores unknown values.
