### ISSUE TITLE
receiving a Kerberos ticket that is incorrect format 

### ISSUE THREAD

**Issue by alosman24** [SteveSyfuhs/Kerberos.NET#23]
Hi Steve, based on convo, 

I keep getting "Unknown Negotiate Extension Signature". I are using a keytab file generated on our dev box which has our entire AD. When i get the kerberos ticket from the client i get that error. You specified that the ticket i am getting is not correct format.

So i think i am not doing the handshake properly to get the right kerberos ticket from browser.  based on your code, 

```
if (!context.Request.Headers.TryGetValue("Authorization", out StringValues authzHeader) || authzHeader.Count != 1)
            {
                context.Response.Headers.Add("WWW-Authenticate", new[] { "Negotiate" });
                context.Response.StatusCode = 401;

                return false;
            }
```

we we send this, we are not getting a kerberos ticket the browser is sending something else. How can i force my browser or cleint to send the correct kerberos ticket, do i need to include something else int he WWW-Authenticate.

Thanks

**Comment by SteveSyfuhs** [comment]
You're setting the header correctly. Without seeing a sample of the ticket I can't say what you're actually getting. You may be getting an NTLM or U2U ticket instead. Have you configured an SPN in AD for the service account that the key tab is for?

**Comment by alosman24** [comment]
Is there a way i can decrypt the ticket to take a look, so i can remove sensitive material before i put it here. 
I've received the keytab file from our server admin folks, but they did generate the file using a SPN.

**Comment by SteveSyfuhs** [comment]
There's a tool here: https://github.com/SteveSyfuhs/Kerberos.NET/tree/master/KerbDump

This likely won't actually be useful though because it's going to bail out with the same error.

A kerberos ticket is encrypted to the key in the key tab file. There's very little information you can read without the key. However its still a valid ticket until it expires. If you want you can email it to me steve@syfuhs.net, or possibly just drop the first 1/2 of the ticket in here. I really just need it to parse the first section to figure out what type of ticket it really is.


________________________________
