### ISSUE TITLE
i can connect with bruce using kinit, but i cannot in a .net core 3.1 project using kerberos.NET libraries

### ISSUE THREAD

**Issue by auriou** [SteveSyfuhs/Kerberos.NET#259]
**Describe the bug**
i can connect with bruce using kinit, but i cannot in a .net core 3.1 project using kerberos.NET libraries

**To Reproduce**
with bruce
![image](https://user-images.githubusercontent.com/1873587/127658196-8e736e85-957b-4d50-a400-8265c74d6a55.png)

using Kerberos.Net in my project, the authentication is doing well but I have an invalid checksum
![image](https://user-images.githubusercontent.com/1873587/127659110-98358873-9180-4c9f-ac0d-27260dde9614.png)

I used "krbtgt/SRP-DEV.LOCAL" for GetServiceTicket method, because this is what is indicated on brice with the kping command
it may not be what to do
![image](https://user-images.githubusercontent.com/1873587/127658578-14128924-a994-4ac0-a4d6-e7ea0e6ce2e9.png)

Error Detail
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Invalid checksum)
  Source=System.Private.CoreLib
  Arborescence des appels de procédure :
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at TestSql.Program.Main(String[] args) in C:\Users\p.auriou\source\repos\TestSql\TestSql\Program.cs:line 29

  Cette exception a été levée à l'origine dans cette pile des appels : 
    [Code externe]

Exception interne 1 :
SecurityException : Invalid checksum

**Comment by SteveSyfuhs** [comment]
Is there a specific reason you're requesting a krbtgt as a service ticket? By all rights that should work and might be a bug, but calling Authenticate() will get you the TGT already so you're just overwriting the existing one.

You might also try passing "krbtgt" instead.
________________________________
From: Philippe AURIOU ***@***.***>
Sent: Friday, July 30, 2021 6:23:21 AM
To: dotnet/Kerberos.NET ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dotnet/Kerberos.NET] i can connect with bruce using kinit, but i cannot in a .net core 3.1 project using kerberos.NET libraries (#259)


Describe the bug
i can connect with bruce using kinit, but i cannot in a .net core 3.1 project using kerberos.NET libraries

To Reproduce
with bruce
[image]<https://user-images.githubusercontent.com/1873587/127658196-8e736e85-957b-4d50-a400-8265c74d6a55.png>

using Kerberos.Net in my project, the authentication is doing well but I have an invalid checksum
[image]<https://user-images.githubusercontent.com/1873587/127659110-98358873-9180-4c9f-ac0d-27260dde9614.png>

I used "krbtgt/SRP-DEV.LOCAL" for GetServiceTicket method, because this is what is indicated on brice with the kping command
it may not be what to do
[image]<https://user-images.githubusercontent.com/1873587/127658578-14128924-a994-4ac0-a4d6-e7ea0e6ce2e9.png>

Error Detail
System.AggregateException
HResult=0x80131500
Message=One or more errors occurred. (Invalid checksum)
Source=System.Private.CoreLib
Arborescence des appels de procédure :
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task1.GetResultCore(Boolean waitCompletionNotification) at System.Threading.Tasks.Task1.get_Result()
at TestSql.Program.Main(String[] args) in C:\Users\p.auriou\source\repos\TestSql\TestSql\Program.cs:line 29

Cette exception a été levée à l'origine dans cette pile des appels :
[Code externe]

Exception interne 1 :
SecurityException : Invalid checksum

**Comment by auriou** [comment]
i want to get ticket like kinit command does. 

But I don't know which service to call, with GetServiceTicket. the goal is to be able to run a sql command in IntegratedSecurity mode which therefore uses kerberos. 

With the classic kinit commands from bruce or krb5 under linux it works, I can then connect to sql server.
But I would like to automate it in my program.

Thanks.

**Comment by SteveSyfuhs** [comment]
All kinit is doing is calling Authenticate(). If you also want it to write to the cache file instead of keeping it in memory then that requires setting a property on the client `client.CacheInMemory = false;`

**Comment by auriou** [comment]
my code is in a docker, the authentication works but no ticket when I do a klist
I load config
var config = Krb5Config.Parse(File.ReadAllText("/etc/krb5.conf"));

![image](https://user-images.githubusercontent.com/1873587/128189670-d32ee73a-e490-41fd-8155-b9cd33743be8.png)

**Comment by SteveSyfuhs** [comment]
I suspect the cache is being written to another file. `/tmp/krb5cc_0` is not a standard path for Kerberos or Kerberos.NET. You can configure the cache to use that path instead with a change to the config file

```
[libdefaults]
default_ccache_name = /tmp/krb5cc_0
```
