### ISSUE TITLE
Support for mutual authentication?

### ISSUE THREAD

**Issue by quietust** [SteveSyfuhs/Kerberos.NET#28]
Most other KRB5 implementations I've used (including mod_auth_kerb) support _mutual_ authentication by default - after the client submits a valid Negotiate token, the server responds with its own `WWW-Authenticate: Negotiate` header containing a Base64-encoded value that the Client can decode in order to confirm that it's actually talking to the correct server.

This library does not appear to support it, at least in its current state - there are symbols defined in Entities/Enums.cs related to mutual authentication, but they are not referenced from anywhere else.

Are there any plans to implement this functionality in the near future?

**Comment by SteveSyfuhs** [comment]
Technically there is already mutual authentication in place because only the holder of the secret can decrypt the ticket. All that final step is doing is affirming it by encrypting the current timestamp against the negotiated session key in the ticket. As an attacker I could just skip this step and most clients wouldn't care, or pass along any responses. This is only useful if your app relies on the session key for message protection.

Do you have a client that does this?

Either way I have considered it, but it's a ton of work because I need an ASN.1 generator. This is small enough that it's a good starting point though. Specifically in the *near* future -- no, sorry.

**Comment by broudy3** [comment]
What about borrowing  ASN.1 generator from [WindowsProtocolTestSuites](https://github.com/Microsoft/WindowsProtocolTestSuites/tree/staging/ProtoSDK/Asn1Base)? It also has the needed [structures](https://github.com/Microsoft/WindowsProtocolTestSuites/tree/staging/ProtoSDK/KerberosLib/Asn1Code/Rfc4120) implemented.

**Comment by SteveSyfuhs** [comment]
This was added in https://github.com/SteveSyfuhs/Kerberos.NET/pull/43
