### ISSUE TITLE
Web sample doesn't work

### ISSUE THREAD

**Issue by BasieP** [SteveSyfuhs/Kerberos.NET#29]
after running the websample i get asked to enter credentials in my browser...
Unsure, i put in the "P@ssw0rd!" i found in the sample into both fields (since i lack the username)

This gives me an InvalidDataException, thrown because he can't detect the mechtype (in TryDiscoverMechType method of the ContextToken class)
It expects my element to have a class 'TagClass.Universal', but it is 'Application'..

Am I doing something wrong?

//offtopic: perhaps good to add a small readme.md to the sample projects, so people like me don't ask stupid questions

**Comment by SteveSyfuhs** [comment]
This is most likely falling back to NTLM via some negotiate mechanism. This is expected if you don't have the required AD environment set up. See the section [Creating a Kerberos SPN in Active Directory](https://github.com/SteveSyfuhs/Kerberos.NET#creating-a-kerberos-spn-in-active-directory) in the main readme.

The fact that it's throwing *that* particular error is however unexpected though. It should be failing gracefully. I can review this if you provide a copy of the ticket it's trying to parse.

**Comment by BasieP** [comment]
The web example doesn't use a keytab file, but uses this construction
```c#
validator = new KerberosValidator(new KerberosKey("P@ssw0rd!")) { ValidateAfterDecrypt = ValidationActions.None };
```

they key my browser generates (after i type in the P@ssw0rd!) is as follows:
```
YIIHHAYGKwYBBQUCoIIHEDCCBwygMDAuBgkqhkiC9xIBAgIGCSqGSIb3EgECAgYKKwYBBAGCNwICHgYKKwYBBAGCNwICCqKCBtYEggbSYIIGzgYJKoZIhvcSAQICAQBugga9MIIGuaADAgEFoQMCAQ6iBwMFACAAAACjggU1YYIFMTCCBS2gAwIBBaEaGxhJREVOVElUWUlOVEVSVkVOVElPTi5DT02iLTAroAMCAQKhJDAiGwRIVFRQGxphYWRnLndpbmRvd3MubmV0Lm5zYXRjLm5ldKOCBNkwggTVoAMCARehAwIBAqKCBMcEggTDQ6q42LX13SnhQOPfGB908eEl+GRSFPllJRpyR7ywo8Cz0Wz+9OUSomwK22xirtqKEvzcSxGORjosiIqeV3OoZtz5vBKdg1bI/3Yin081R5jPlm9/FhnWT6pT7ryQFFTyKpyF9hNAXOpOklJA4WLIlOaRGRTPtKW5ThNFuk76stoAAvQJYVImvI3ePPj1ryVb9FzeWL/FZkYfrjwtK4IUqOy3fccxN/UZ01GDVJn4urCDf7gvy357DQ+4A8Ih/yevVnsEBoTEsAZqi6j7P//5OzpN6k7Ton7+KE2EDoZhQj+zzGdQ3W+LxqaeE3O+3u6xsoH4DERI72ZwR1WLEYclKoTj4+qo7RiVRVN5rIwMN5a1qqzuaVYrxuvTEN7tXdAarecMFwJsNbJv/aIzbV5kWRoHzLlNgQiv6avkBegBwsr4bnCT0g4ChRULp2IcP/wvfagVo7MhqJ4B3dzWNp34QWo6iHG/LsvbK8Lz2+H+CPwdQKa6CX7jtrQnlyyw71o62UKu2wRgEg02WpiyyjdlVAFd3bVBp+dnGtGkqOiVF0+3HiKYXvTsfTE/jTk+IrUzGXkbJSDx0tnMSlFDKq0QXJhEIGow6cxo6KGXdS7UHbY0ldat2YrH2QD4msSv4a86QZGLWLDOy6OI3RFOK/uQNOrWqXWZ8oie/gO2410sFXn4bAtSaTkVliEOg+FNJNWb9TMGK9MDdeygTwLqlr3St0Fv5Jt51iaIXUqXQqKxtU/WXo1pnngvJfNCLSIA7iLbBmOOvLULR/mi9eWD8FTRQqlnEigoUwShKmJZ6bcAqr6Q8Uf+jQj5JQfAhRYwWIom/7KeCU3oyWFPbyPlK8qLWd3LboNYJEy8/wFoMszH6EFCEu3KC0y/+MFmYmLw15Ay2GQkZnD8pN3WjRvkKJFfj6zCSJUk7IX7/R3KZNLsJfzQN/4Uk/ekJvz05L/G5qNyW1At4RBJC4doUSYhuIDGqwqYqxGvuRP1cdODmr1XcHiPAXfxoD5H+UZbzbLxRprrhW5cW6iKxsVGyGXdqQQK8FchOJ0GDUczV3zjBWVYSBgYmF/LC1hDdt55F1oozMDDWhUJcxBXTXJm7pbOArUQapCA3fR6z08wRoY3FIrW9FyaPNbeUNqhk0sPxzzo0RCZdnVelgbU2QfdhM6KvMBkDbNjbNA+BhEyUA2EbSWLMwnLPiFKtUXb3IhBYVWs+4BZJJZoJsVt7POJyH7UW6EWFjYdebJQK5SbwiqvtQcq8b+bw3UiSpXrSDtdqLnrdNq7iL9Dtbm2Twepn2i6ryfWz2rSsvZMe3uW/J2rKx19jaQ5liemLJnKGwThRN+1zBu5cs2EM7rRmsXWAD3EWpWKr6HhIrifrTfpq2knUtOUHvqgCkYvUCJfdbdvdwYSXrAVIcgFNQx26jF5rSYJ8EceQztHfoSL1f9DwWcL6dVYykKE5XZ3Apc1RkKEfSYKRFTeG4ZgGFHADu8lYLbo4/dRI+4Pa2FbguyMf/ddFaMb8tHDFhACjwBafj8jsyrQhL6OTYyteXD9zfACVjiZmtCN/Axi2+i96mGRQ0072wbbXBhN7TX9HCnfAZ4K3dCLxjQDrP3CkccAQ4xe+/XOHUF/OKrS/6SCAWkwggFloAMCAReiggFcBIIBWHjbFqJT3hYbgxQEQNwsOjo1A1bIADpSkNIb13NbKsAaGtNWIoPXxjSBlVfqoegKKIgezYH3TRXubnIsE99YyfPVf9g3sxwgt7er0Df4VHjvZScCq60un6P6ETTd8W2E1Rvc2IYksCy1T64OOKI9Bg5rvdaa6TypgPG9EpSSPOW/7PeMqwkXPqN6ZetFTkX93bDtU1uQF6ZxPDkmIRUarzkRSDsvQaGnYzgwOA4NCJsafLsdzHhsEFvt68nnWma6zp22NKjg4HzazzNlrP0gJBuXE0M5ymI+ocFS2AdnamMZK/TJo9SEOYiQIUIW3J+hsglTMJSFe3WeF7CBTFAc9L0zksmhw36GnzKjwrTk0isazedjnr3iqf+Qu8OU1WcPsqMH+YobdbMoVG52CjGZfhxqRp2kct7yIYLWZfQWwaw/cLgQr5GeDglRs8aG7jQdbC76OAn6ulZL
```

**Comment by SteveSyfuhs** [comment]
That is a particularly interesting ticket because it contains no data whatsoever. The error is technically correct in that regard, but I've added a bit more detail in the handling of it to make it clearer. 

As for why its not working correctly... Active Directory is not able to generate a kerberos ticket because it can't determine what service account it should encrypt it against. As such the client is sending a null negotiate message to the server so the server can renegotiate using (probably) NTLM.

The section I referenced above provides a link to documentation for setting up a test environment. The keytab is one option, but all you need is the `P@ssw0rd!` password set on the service account, which matches what the sample is expecting.

**Comment by BasieP** [comment]
I do understand all of this, but it kinda renders the websample (provided on this github site) useless...
Ofcourse i want get a real AD involved, but i thought there was an oppertunity to do so without one (since you provided an example without one)..

**Comment by SteveSyfuhs** [comment]
`KerberosKey` represents the secret used by the service account to decrypt kerberos tickets. It can be used with a raw string password e.g. `P@ssw0rd!`, the derived key (hash of raw+salt), or a collection of derived keys in the form of a Keytab.

The point of the library is to receive kerberos tickets and decrypts them. That's it.

Active Directory is inherently required in all live samples because this library doesn't generate tokens, and in the case of a web sample has no way to feed the ticket to the browser so it can present it to the web server.

**Comment by BasieP** [comment]
Hi Steve,

First of all i don't want to sound ungrateful, since i love you taking the time to share this library. I know the library does only the 'magic' in between and we still have to do 2 things ourselves.
1. connect our app to the AD
2. connect our client to the AD (or use a browser)

I think i misunderstood the samples for 'guides' to get at least the first of those things done..

That being said, i read the link you posted and some other sites about keytab files.
They all involve doing stuff in the AD. In the past, while using the old .Net framework, i only needed a serviceaccount to do the authentication part of kerberos. (in IIS, you configured the service account in the applicationpool).
Although i don't know if it has anything to do with the claims part of kerberos (which i would like to use), i wonder why i have to do all these AD changes.
Fact is that i'm a developer inside a big corporation, and they don't let me 'play' on their AD....

How does that work?

**Comment by SteveSyfuhs** [comment]
The difference is that .NET hands the ticket off to Windows and Windows does a lot of magic to decrypt it. The service account still needs to exist in AD. In the case of using e.g. Network Service or SYSTEM in IIS, Windows still has a service account, but instead of a named account it uses the machine account, which was registered when the machine was joined to the domain. 

When hitting the web site in the browser your browser attempts to look up the site domain name in AD so AD knows what password to encrypt the kerberos ticket to. The website receives the ticket and decrypts it because it also knows that key.

This library is designed to bypass all the Windows niceties and do the magic itself. That still means the browser will try and look up the site in AD, and request a ticket from AD. It needs an account of some sort in AD to know what key to use. The difference is that this library can't use the machine account because it doesn't have permission to the password, and it's intended to be used on non-domain-joined systems anyway (otherwise why not just use the Windows stuff?).

I'm not sure where claims fit in here. Claims are just arbitrary values stuck in the kerberos ticket. That too has to be [configured ahead of time](https://syfuhs.net/2017/07/29/active-directory-claims-and-kerberos-net/) in AD.

**Comment by BasieP** [comment]
i get all that, but so far i couldn't get it to work because i somehow only get examples like this:
https://blogs.technet.microsoft.com/pie/2018/01/03/all-you-need-to-know-about-keytab-files/

Since i allready have a serviceaccount i figured i could get started using kerberos (like we used to in old .Net)
Now i somehow need keytab files, and the tools for creating them somehow want to write shit in the AD (a SPN), which i didn't need before.
Since i'm not a AD administrator, i can't execute those commands, resulting in... no keytab files.. Therefor no way of connecting your library to an AD.

So, is there a simple example of how to connect your library to and AD without being AD administrator?

**Comment by igor-moskvitin** [comment]
@BasieP i think that you cannot create SPN without admin AD privileges. and important thing - if you ask your admins to do it for you, notice that if service name like `HTTP/service.domain.com` already work in IIS and using windows authentication - you can get some troubles with decrypting tickets.
Best option to test this stuff - hyper v with server, that contains AD.

**Comment by PeterHalsted** [comment]
Btw. if you work as a .NET developer in a big company, chances are that you have an MSDN subscription. If so, you have Azure credit that you could use to build you own small closed test environment for learning about how this stuff works :)

There are lots of great articles on how to set up such an environment and one of them is: https://docs.microsoft.com/en-us/office365/enterprise/base-configuration-dev-test-environment

**Comment by BasieP** [comment]
@PeterHalsted thanks. good links and i didn't know about Azure (I have msdn indeed)

**Comment by BasieP** [comment]
oke... still not getting it to work..

I got a keytab file, feed it to my websample (right from this github page) like so:
```
validator = new KerberosValidator(new KeyTable(File.ReadAllBytes(path)));
```

When i start the sample, i don't get promped for a password in Chrome (my laptop is not domain joined).
I know chrome tends to start sending a ticket of the logged in user (although that would be my local pc) but after that fails i should expect a login prompt.
Also the exception i get is this:
```
Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
```
which i bet is great when you are debugging your own crypto implementation, but not so much when you are a user of a library...
The negotiate header at this time was:
```
Negotiate YIGCBgYrBgEFBQKgeDB2oDAwLgYKKwYBBAGCNwICCgYJKoZIgvcSAQICBgkqhkiG9xIBAgIGCisGAQQBgjcCAh6iQgRATlRMTVNTUAABAAAAl7II4gkACQA3AAAADwAPACgAAAAKAO5CAAAAD0RFU0tUT1AtUThSRTBVRVdPUktHUk9VUA==
```


when i added an other 401 header response in the catch of the middleware, to get chrome to give me a prompt, and I put in my domain credentials (inclusing the domain), i get the following exception:
```
Exception of type 'Kerberos.NET.Entities.UnknownMechTypeException' was thrown.
```
not unexpected when this is the negotiate header:
```
Negotiate TlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAKAO5CAAAADw==
```

**Comment by SteveSyfuhs** [comment]
The first encoded value is NTLM. Not sure why it can't detect that. It is explicitly designed to look for it and error out. This is a bug I'll look in to.

The second value is an empty negotiate message. My guess is your browser is trying to solicit the correct negotiate package from the server. My follow up guess is that it's doing that because your machine isn't domain joined. In a DJ scenario it's going to prefer Kerb, but since it's not DJ'ed it may not have any idea.

When entering your creds you're going to need line of sight to a DC, and going to need to provide a realm, either realm\user or user@realm so Windows can DC locate properly.


________________________________

**Comment by SteveSyfuhs** [comment]
I wanted to follow up on this as I had some time to dig in a bit further. 

In both cases each request is NTLM. The first is a SPNEGO-wrapped NTLM negotiate message. I suspect this means the DC could not find an SPN that matches the hostname you're trying to connect to at all.

The second case is a straight NTLM negotiate message, without any SPNEGO wrapper. I'm not sure under what condition it attempts to do this, but I'm guessing it happens when there's no way it can even attempt Kerberos so it won't try.

In either case you have AD config issues. You've created the keytab for a particular service account but you haven't configured the account to allow Kerberos using the hostname you're trying to connect to.

E.g. if your browser is connecting to site https://app.foo.com/whatever, your service account needs an SPN registered as "HTTP/app.foo.com"

I will push a package update tonight that tries to handle the above formats (though be aware all its going to do is detect and throw exceptions).
