### ISSUE TITLE
Does the KeyTable implementation supporting "generating" a proper keytab file?

### ISSUE THREAD

**Issue by ebekker** [SteveSyfuhs/Kerberos.NET#320]
**Describe the bug**
I was testing out the ability to generate a keytab file using the built-in `Kerberos.NET.Crypto.KeyTable` class by providing a `KerberosKey` entry and then writing out the keytab to a file.  However, when I tried to provide the generated keytab to a Kerberos client application (e.g. `kinit` on Linux), the credential (key) stored within does not work.  When I performed the same test, except using the built-in `ktutil` tool to generate the keytab with the same set of parameters (Principal, Realm, Encryption Type, Password, KVNO, etc.) then `kinit` is able to successfully complete (i.e. successfully obtains new tickets).

**To Reproduce**
Here is some sample code of the basic procedure that I followed.  For the sample, let's pretend we have an AD user `jdoe` in a domain `example.com` with a password of `$00perSecret`.  The sample code:

```csharp
var namesList = new List<string>() { "jdoe" };
var princName = new Kerberos.NET.Entities.PrincipalName(
    Kerberos.NET.Entities.PrincipalNameType.NT_PRINCIPAL,
    "EXAMPLE.COM", namesList);

var krbKey = new Kerberos.NET.Crypto.KerberosKey(
    "$ooperSecret", princName, null, null, null,
    Kerberos.NET.Crypto.EncryptionType.AES256_CTS_HMAC_SHA1_96)

var keyTab = new Kerberos.NET.Crypto.KeyTable(krbKey);

using var stream = System.IO.File.OpenWrite("./test1.keytab");
using var writer = new System.IO.File.BinaryWriter(stream);
keyTab.Write(writer);
```

And the equivalent example using the Linux native `ktutil` tool:

```bash
$ ktutil
ktutil:  addent -p jdoe@EXAMPLE.COM -k 1 -e aes256-cts-hmac-sha1-96 -password
Password for jdoe@EXAMPLE.COM:   (password entered as above)
ktutil:  write_kt ./test2.keytab
ktutil: exit
```

**Expected behavior**
Using both of these generated samples, I can inspect the content of the keytab files using some Linux-native tooling:

```bash
klist -k -t ./test1.keytab -K -e
klist -k -t ./test2.keytab -K -e
```
The structure of both sample files appears correct, showing the same content (encryptiong type, principal/realm names, etc.).

However, when I try to use these keytabs as credential inputs to the `kinit` tool for obtaining new tickets, `test1.keytab` fails but `test2.keytab` succeeds:

```bash
## Fails
kinit -k -t ./test1.keytab jdoe@EXAMPLE.COM
kinit: Pre-authentication failed: Permission denied while getting initial credentials

## Succeeds
kinit -k -t ./test1.keytab jdoe@EXAMPLE.COM
## klist now shows successfully obtained tickets
```

**Screenshots**
_(n/a)_

**Additional context**
Incidentally, if I use the `KeyTable` class to read in an existing keytab file and then simply write its contents back out, I can then use the written out keytab file as input to `kinit` successfully.  This would seem to indicate that `KeyTable` is structuring the content correctly, but perhaps the _transformation_ of the input password using the specified encryption type is not properly handled.

**Comment by SteveSyfuhs** [comment]
The structure is fine.

In both cases it's guessing the salts for the keys and in the ktutil case it's either guessing correctly or probing the KDC explicitly for the salts. It's impossible to consistently derive the salts based solely on principal name so I'd guess ktutil is actually querying to KDC.
________________________________
From: Eugene Bekker ***@***.***>
Sent: Wednesday, October 12, 2022 11:14:04 PM
To: dotnet/Kerberos.NET ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dotnet/Kerberos.NET] Does the KeyTable implementation supporting "generating" a proper keytab file? (Issue #320)


Describe the bug
I was testing out the ability to generate a keytab file using the built-in Kerberos.NET.Crypto.KeyTable class by providing a KerberosKey entry and then writing out the keytab to a file. However, when I tried to provide the generated keytab to a Kerberos client application (e.g. kinit on Linux), the credential (key) stored within does not work. When I performed the same test, except using the built-in ktutil tool to generate the keytab with the same set of parameters (Principal, Realm, Encryption Type, Password, KVNO, etc.) then kinit is able to successfully complete (i.e. successfully obtains new tickets).

To Reproduce
Here is some sample code of the basic procedure that I followed. For the sample, let's pretend we have an AD user jdoe in a domain example.com with a password of $00perSecret. The sample code:

var namesList = new List<string>() { "jdoe" };
var princName = new Kerberos.NET.Entities.PrincipalName(
    Kerberos.NET.Entities.PrincipalNameType.NT_PRINCIPAL,
    "EXAMPLE.COM", namesList);

var krbKey = new Kerberos.NET.Crypto.KerberosKey(
    "$ooperSecret", princName, null, null, null,
    Kerberos.NET.Crypto.EncryptionType.AES256_CTS_HMAC_SHA1_96)

var keyTab = new Kerberos.NET.Crypto.KeyTable(krbKey);

using var stream = System.IO.File.OpenWrite("./test1.keytab");
using var writer = new System.IO.File.BinaryWriter(stream);
keyTab.Write(writer);

And the equivalent example using the Linux native ktutil tool:

$ ktutil
ktutil:  addent -p ***@***.*** -k 1 -e aes256-cts-hmac-sha1-96 -password
Password for ***@***.***:   (password entered as above)
ktutil:  write_kt ./test2.keytab
ktutil: exit

Expected behavior
Using both of these generated samples, I can inspect the content of the keytab files using some Linux-native tooling:

klist -k -t ./test1.keytab -K -e
klist -k -t ./test2.keytab -K -e

The structure of both sample files appears correct, showing the same content (encryptiong type, principal/realm names, etc.).

However, when I try to use these keytabs as credential inputs to the kinit tool for obtaining new tickets, test1.keytab fails but test2.keytab succeeds:

## Fails
kinit -k -t ./test1.keytab ***@***.***
kinit: Pre-authentication failed: Permission denied while getting initial credentials

## Succeeds
kinit -k -t ./test1.keytab ***@***.***
## klist now shows successfully obtained tickets

Screenshots
(n/a)

Additional context
Incidentally, if I use the KeyTable class to read in an existing keytab file and then simply write its contents back out, I can then use the written out keytab file as input to kinit successfully. This would seem to indicate that KeyTable is structuring the content correctly, but perhaps the transformation of the input password using the specified encryption type is not properly handled.

**Comment by ebekker** [comment]
Doh!  This was totally my mistake.

It turns out that the source of the bug was totally due to a variation that I hadn't fully documented above and didn't even consider.

In practice both the KrbNET and KTUtil were actually running from different directories, and in the KTUtil test it was accessible to the target principal, and in the KrbNET it was not.  So the keytab files that was being generated by KrbNET simply couldn't be read by the `jdoe` account when it was trying to do `kinit`.

Once I properly accounted for this, the Kerberos.NET-generated keytab works great.

Thanks for such a useful library and all the details you document in your blog!  With this last bit we're able to successfully use gMSA accounts on our Linux hosts.
