### ISSUE TITLE
question: cross domain kerberos setup

### ISSUE THREAD

**Issue by BasieP** [SteveSyfuhs/Kerberos.NET#325]
First of all, great job on this library.

I have big trouble setting it up in our (way too) big organization.

The setup is pretty simple.
We have domainA.com as primary domain with all the users.
and domainb.com which is where i have to host my app.
domainb is joined with domaina, where b trusts a, but a doesn't trust b.

I host my website on idp.domainb.com.
The application runs under a serviceaccount from domainA.com.
the user has a SPN (HTTP/idp.domainb.com) and a keytab file which is loaded by kerberos.Net.

The user (domain joined in domaina.com), goes to my website (https://idp.domainb.com).
i send a http 401 with www-authenticate: negotiate header.
The browser receives it, but doesn't send any ticket..
i tried adding the domain (*.domainb.com) to the 'local intranet' zone, but that didn't do anything..
what am i missing?

I did try it with a browser in domainb, in that case i did receive a ticket, but that looked like a ntlm ticket.
This is weird to me, cause the computer and user are both from domainb.com and the site is also from domainb.com.. So i would think that this should result in a kerberos ticket.. And now i'm confused.. 

Also , i'm under the assumption that this possible..
But some others in my organisation are telling me it doesn't work cause the domains are not 2-way joined..

The flow I THINK should happen is this:
1. user goes to website (https://idp.domainb.com)
2. website gives 401
3. browser checks if domain is in local intranet zone (therefore trusted)
4. browser (or accually the OS) retreives kerberos token for this domain (which works, because the AD has a SPN for HTTP/idp.domainb.com)
5. browser sends kerberos ticket to server
6. server can decode the ticket cause it uses the user account (or just keytab belonging to the account??) the ticket is encoded with
7. voilá

Is that flow correct? i can't find it anywhere on the internet.
Only simple flows there saying 'browser does magic and sends ticket'. But nowhere it says on what basis the browser (or OS) decides it should send the ticket, and why the whole principle works...

I have two concrete questions:
1. Do I need a keytab file AND run my service under a serviceaccount? or is it either of those?
2. Does the browser send a kerberos key to other domains purely based on the domain being:
 a. in the local intranet zone
 b. exists as SPN in it's AD

**Comment by SteveSyfuhs** [comment]
Where is the library coming into play? Is it the client requesting the ticket or the server accepting the ticket?

In the server case that sounds like the service principal isn't configured with the right SPN so it's falling back to NTLM. That gets a bit tricky to diagnose specifically, but a network trace of the client sending a request to the DC will tell you specifically what it's asking for.

In the client case, that's more complex because it's somewhere between the DC not responding with a referral to the other domain, or the client not knowing to request it from the other domain.
________________________________
From: BasieP ***@***.***>
Sent: Tuesday, November 8, 2022 10:20:19 AM
To: dotnet/Kerberos.NET ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dotnet/Kerberos.NET] question: cross domain kerberos setup (Issue #325)


First of all, great job on this library.

I have big trouble setting it up in our (way too) big organization.

The setup is pretty simple.
We have domainA.com as primary domain with all the users.
and domainb.com which is where i have to host my app.
domainb is joined with domaina, where b trusts a, but a doesn't trust b.

I host my website on idp.domainb.com.
The application runs under a serviceaccount from domainA.com.
the user has a SPN (HTTP/idp.domainb.com) and a keytab file which is loaded by kerberos.Net.

The user (domain joined in domaina.com), goes to my website (https://idp.domainb.com).
i send a http 401 with www-authenticate: negotiate header.
The browser receives it, but doesn't send any ticket..
i tried adding the domain (*.domainb.com) to the 'local intranet' zone, but that didn't do anything..
what am i missing?

I did try it with a browser in domainb, in that case i did receive a ticket, but that looked like a ntlm ticket.
This is weird to me, cause the computer and user are both from domainb.com and the site is also from domainb.com.. So i would think that this should result in a kerberos ticket.. And now i'm confused..

**Comment by BasieP** [comment]
Hi,

The kerberos.net component is in our webserver and is suppost to validate the incomming token.

In the server case:
The website is in idp.domainb.com and the server i'm testing from is member of that same domainb.com.
But, there is no SPN in domainb that corrosponds with idp.domainb.com. Is that the reason it falls back  on ntlm?

In the client case:
The client member of domaina.com
It visits a site in domainb.com (idp.domainb.com)
There is an SPN in domaina.com HTTP/idp.domainb.com.
So it simply should create a kerberos ticked based in that spn right?
I don't understand the part of your answer where you say it has to contact the other domain.
Why does he has to do that? There is nothing in the DC of domainb.com that is interesting.. the spn, serviceaccount and keytab are from domaina.com

**Comment by SteveSyfuhs** [comment]
I follow now. I misunderstood your setup.

If you're receiving an NTLM token then that definitively means the client requested an SPN that isn't mapped (alternatively the client doesn't have line of sight to a DC, but that's unlikely in this case). Therefore, the client requested http/<something-else> when it should have requested http/idp.domainb.com. The _usual_ cause of this with web things is that the name you're connecting to is a CNAME, and the SPN that got requested is the canonicalized form of that CNAME (idp.domainb.com -> prd-foo-idp-123.corp.internal.long.name.com => http/prd-foo-idp-123.corp.internal.long.name.com).

**Comment by BasieP** [comment]
Hmm i think you misunderstand the setup now. I use the full domain names.


Forget the whole testing from a server scenario inside domainb.com

Just 1 scenario, same as in startpost.

Client is in domaina, and domainjoined.
Server is in domainb, which is has a trust with domaina (b trusts a, a doesn't trust b)

- The client (from domaina.com) sends request to the server (https://idp.domainb.com).
- It receives a 401 with www-auth header.
- Then for 15 seconds nothing happens.

In my opinion, the browser (or accually the OS) is asking for a kerberos ticked in those 15 seconds.
It askes to the the DC of domaina.com
Domaina.com finds the SPN for (HTTP/idp.comainb.com)
The KDC should create a ticket right?
Or am i missing a step?

**Comment by SteveSyfuhs** [comment]
Yes, that is more or less what's supposed to be happening. Use a network capture tool like Wireshark and you should be able to see what's going on. In practice 15s is a very long timeand it should only really take sub-second, unless you're hitting network issues.
________________________________

**Comment by BasieP** [comment]
Yeah thats what i thought.
15 seconds is surely some timeout.

And does the dc of domaina.com have to talk to the dc of domainb.com? Cause
a lot of ppl in our big organization that (just as I) only know half of
Kerberos say that the DC's of both domains need to chat...

But i can't imagine why, cause domain b doesn't do anything other then
hosting a site. It might as well be any other domain right?
(like for example microsoft.com. And it should work if i gave them a keytab
file)

**Comment by SteveSyfuhs** [comment]
Domainb shouldn't be coming into play at all if domainA has both the users and service principal.
________________________________

**Comment by BasieP** [comment]
Got it working.

The cause:
my domainname (idp.domainb.com) was created by someone who thought he should only use C-names.
So he created a A-record idp-vip.domainb.com, and then created a C-Name record that points to that A-record.

Result: my browser was requesting a kerberos ticket for SPN idp-vip.domainb.com instead of the SPN I created, idp.domainb.com...
Took us a lot of time to figure that out...
