### ISSUE TITLE
How to get issuing KDC host from ticket?

### ISSUE THREAD

**Issue by jcuzzi** [SteveSyfuhs/Kerberos.NET#339]
Is there a way to retrieve the KDC host name that issued a ticket from the ticket response?

“Klist.exe get” provides this information, but I’m unsure of where it comes from, and don’t see any related properties in this library which would identify the server.

**Comment by SteveSyfuhs** [comment]
Nope. The ticket doesn't contain this information. The only reason klist knows it is because Windows knows which DC it sent the request to and caches that information next to the ticket.
________________________________
From: jcuzzi ***@***.***>
Sent: Tuesday, April 18, 2023 8:54:15 PM
To: dotnet/Kerberos.NET ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dotnet/Kerberos.NET] How to get issuing KDC host from ticket? (Issue #339)


Is there a way to retrieve the KDC host name that issued a ticket from the ticket response?

“Klist.exe get” provides this information, but I’m unsure of where it comes from, and don’t see any related properties in this library which would identify the server.

**Comment by jcuzzi** [comment]
Thanks. So if I were to first query DNS for KDCs, I could loop through them and send a request to each one and associate the host with the response. 

Is there a way to override the server which the request is sent to using LSA or SSPI? Or would this library be best?

**Comment by SteveSyfuhs** [comment]
What exactly are you trying to accomplish?
________________________________

**Comment by jcuzzi** [comment]
Trying to test if a specific KDC is the actual server that issues the ticket, to ensure the server is functioning correctly.
________________________________

**Comment by SteveSyfuhs** [comment]
I guess I'm still not following. All KDCs issue identical tickets, or at least should issue identical tickets. From the outside, the tickets _are_ identical, so you'd need to get their key to decrypt them to see the contents. The only thing that can know where the ticket originated is the client. The only thing that can decrypt the ticket, nominally, is the service that the ticket is intended for. So, I'm not entirely understanding what you're trying to accomplish. Are you just wanting to make sure that a particular KDC is online?

If you want to specify a particular KDC for the client to communicate with you can use the `KerberosClient.PinKdc(string realm, string kdc)` method to pin all requests to a specific machine. Windows has some functions that let you pin DCs, but those are machine-wide.

**Comment by jcuzzi** [comment]
Yes, the purpose is to ensure that a particular KDC is online and responding to requests. Optimally, I would want to use the context of the currently logged in user to make the request.

**Comment by SteveSyfuhs** [comment]
Those are mutually exclusive requirements in Windows. At best you can specify which DC to communicate with at the machine level. You can pick arbitrary KDCs with `KerberosClient`, but you don't get to use the current user's Windows logon credentials to do so.

**Comment by jcuzzi** [comment]
Understood. Thank you for your expertise. I may end up parsing the output of klist, although it pains me to do so.
