### ISSUE TITLE
Unknown Negotiate Extension Signature error

### ISSUE THREAD

**Issue by liatru** [SteveSyfuhs/Kerberos.NET#4]
Hi, 

I tried creating a custom authenticator using .net core 2, and Kerberos.NET package (using a keytab validator) but I'm always getting this error of: Unknown Negotiate Extension Signature..
from this file:
Kerberos.NET/Kerberos.NET/Entities/NegotiateExtension.cs

Is there a reason for the hardcoded signature here? 
What can I do to bypass this?

Thanks,
Liat

**Comment by SteveSyfuhs** [comment]
What's the text of the exception? The hardcoded signature is as per the specification for NegoEx with Kerberos.

In any case, NegoEx isn't actually supported by this library because it requires a multi-stage handshake that this library isn't equipped to handle. It's expecting a Kerberos ticket immediately.

That said, seeing it go through the negotiate process is a good indicator that you haven't configured an SPN correctly. AD can't associate your service with an account in AD to generate a proper kerberos ticket, so it issues a negotiate request to collect more information on how authentication should proceed.
