### ISSUE TITLE
Support for S4U2Self & S4U2Proxy

### ISSUE THREAD

**Issue by macsux** [SteveSyfuhs/Kerberos.NET#50]
**Is your feature request related to a problem? Please describe.**
Customers are transitioning to OAuth2 based flows but still need to support systems that talk Kerberos. We're looking to offer an OAuth2/STS server that can exchange one type of tickets for another. 

**Describe the solution you'd like**
We would like ability to use Kerberos.NET to leverage S4U2Self & S4U2Proxy extensions to obtain Kerberos tickets on behalf of clients and then get a service ticket to destination service. 

**Describe alternatives you've considered**
ADFS is not an option in this case

**Comment by SteveSyfuhs** [comment]
What's the expected flow here? Can you walk me through an E2E of a client app calling the IdP?

Is the intent to have support within the client implementation or the KDC implementation?

**Comment by macsux** [comment]
The conceptual flow would work as following:

1. Client obtains an openID/oauth2 token from oauth2 idp. One of the scopes in token is the calling app's identity
2. Client calls an endpoint on the STS presenting oauth2 bearer token. One of the parameters to this endpoint is target SPN
3. STS validates oauth2 token and extracts caller's identity out of it. It uses this to do S2U4Self request
4. STS uses the parameter from step 2 to obtain a ticket to the specified service on behalf of the app
5. Ticket is returned to the app to be attached to request to target service

This flow can also be reversed to transition from kerberos tickets to oauth2 tickets. This also removes the need for apps to take on hard dependencies on kerberos libraries or use SSPI/GSSAPI to obtain tickets and mix and match new authentication with old in seamless workflows allowing gradual modernization. 

Potentially in future, when running on kubernetes the logic to attach tickets to outgoing requests and protocol transition interactions can be externalized into sidecars to increase reusability.

We're seeing a lot of desire from our clients to move into this direction, but dependencies on Kerberos authentication in their apps and need to integrate with other apps that cannot be modernized (switched over to oauth2) act as a big bottleneck to modernization.

**Comment by SteveSyfuhs** [comment]
Understood. It sounds like this primarily will need to be implemented in the client and validator, and then round off support in the KDC.

**Comment by SteveSyfuhs** [comment]
First pass of _S4U2Self_ here: https://github.com/SteveSyfuhs/Kerberos.NET/compare/adding-s4u?expand=1

It's only the client side. Haven't gotten to the server side yet. Proxy requires a little more work. Not entirely sure what's going wrong.

**Comment by SteveSyfuhs** [comment]
FYI, I've created a PR for S4U proxy support. I'll let it sit for a bit for folks to review if you're interested.

**Comment by Alexander9107** [comment]
Hi. I've got a similar case. The setup is:
a Windows domain user is authenticated on a machine1 and uses a web-browser to run a web app.
the web app is doing http requests to the web-api (.net core) being hosted on another server2. the web api needs to convert the request into an sql request and send it again over http to a database being hosted on server3 (the database supports http interface) on behalf of the Windows domain User. The database also supports Kerberos protocol as an external authenticator for existing users. The main point here is that upon one web api request there might be a need to make more than one http request to the db.
The flow is:
1) the user is making initial http request to the web api and is rejected with http 401 and www-authenticate: negotiate
2) the browser is getting a TGS from KDC and repeats the http request to the web api with the ticket in Authorization header.
3) now, AFAIU the web api needs to authenticate itself to KDC (using web api domain service account) by getting TGT and then to get TGS by doing S4U2Self request.
4) Next the web api needs to make a S4U2Proxy request to get a TGS on behalf of the User to interact with the db.

please check my approach and suggest what needs to be fixed if there's anything wrong or confirm if it's correct:
```
            var keytab = new KeyTable(File.ReadAllBytes(_keytabPath));
            await kerberosClient.Authenticate(new KeytabCredential(ServicePrincipal, keytab));

            // Get a TGS for the user (S4U2Self) - This allows API to impersonate the user
            var s4u2SelfTicket = await kerberosClient.GetServiceTicket(API_SPN, s4u: fullyQualifiedUserPrincipalName);

            // Now, the web API can request DB on behalf of the user using S4U2Proxy
            var dbTicket = await kerberosClient.GetServiceTicket(DB_SPN, s4uTicket: s4u2SelfTicket.Ticket);

            returnValue = Convert.ToBase64String(dbTicket.EncodeGssApi().ToArray());
```

the problem here is that i am getting the following error:

> Kerberos.NET.KerberosProtocolException: KDC KDC_ERR_S_PRINCIPAL_UNKNOWN: Server not found in Kerberos database
>    at Kerberos.NET.Transport.KerberosTransportBase.CheckError(ReadOnlyMemory`1 response) in D:\a\1\s\Kerberos.NET\Client\Transport\KerberosTransportBase.cs:line 70
>    at Kerberos.NET.Transport.KerberosTransportBase.SendMessage[T](String domain, ReadOnlyMemory`1 req, CancellationToken cancellation) in D:\a\1\s\Kerberos.NET\Client\Transport\KerberosTransportBase.cs:line 112
>    at Kerberos.NET.Client.KerberosClient.RequestTgs(RequestServiceTicket rst, KerberosClientCacheEntry tgtEntry, CancellationToken cancellation) in D:\a\1\s\Kerberos.NET\Client\KerberosClient.cs:line 1201
>    at Kerberos.NET.Client.KerberosClient.RequestDecryptedTgs(RequestServiceTicket rst, KerberosClientCacheEntry tgtEntry, CancellationToken cancellation) in D:\a\1\s\Kerberos.NET\Client\KerberosClient.cs:line 912
>    at Kerberos.NET.Client.KerberosClient.GetServiceTicket(RequestServiceTicket rst, CancellationToken cancellation) in D:\a\1\s\Kerberos.NET\Client\KerberosClient.cs:line 747
>    at Kerberos.NET.Client.KerberosClient.GetServiceTicket(String spn, ApOptions options, String s4u, KrbTicket s4uTicket, KrbTicket u2uServerTicket) in D:\a\1\s\Kerberos.NET\Client\KerberosClient.cs:line 1071

So, the problem might be in my code and/or in AD configuration. Your review help will be much appreciated.
