### ISSUE TITLE
How to acquire existing token without providing password again

### ISSUE THREAD

**Issue by Sentoj** [SteveSyfuhs/Kerberos.NET#89]
Hello,

I have seen the sample where a client is authenticated using username and password. However, some libraries (maybe this one too) support the use case where we want to just acquire the current Kerberos ticket seamlessly without having username/password passed as inputs (so without prompting the user again to enter their credentials because they will have already logged in).

In NSSPI, that is known as the "current context" for client or server.

Is there something similar in this library? 

Example:
var client = new KerberosClient();
var kerbCred = new KerberosCurrentClientCredential(); // not Password credentials
await client.Authenticate(kerbCred); // or server.Authenticate() to get a ticket
var ticket = await client.GetServiceTicket("host/appservice.corp.identityintervention.com");

Thanks

**Comment by SteveSyfuhs** [comment]
The credential cache is not persistent across client instantiations by design. This prevents cross-client leaks. The simplest thing to do is keep the `KerberosClient` or `KerberosClient.Cache` around for the lifetime of whatever you're doing and/or implement your own cache. Under the covers it's basically just a `ConcurrentDictionary<>` matching the service name to a ticket for the authenticated user.

However, if you're looking to create a `KerberosClient` and just grab credentials off the currently logged on user in Windows then you should just use SSPI. There's no way to extract the creds from Windows (by design) to use in the initial authentication of the client, and it's not intended to be a wrapper around SSPI.

**Comment by Hochman85** [comment]
I see. I am actually using SSPI and got to a point where I am able to get Kerberos token off the currently logged on user. All that "client-KDC" journey without using Kerberos.NET.

However, the next step for me would be to use that Kerberos token and somehow build AP-REQ so I can send it from client to AP (application server).

Maybe I have to combine two libraries here: SSPI and Kerberos.NET. If you could explain to me how to use Kerberos.NET.Client.ApplicationSessionContext's ApReq please, that'd narrow things down I suppose.

Thanks for your help.

**Comment by SteveSyfuhs** [comment]
The blob of bytes the ISC call gave you is an Ap-req in a GSS wrapper. That's normally what you send to the server. You usually don't send raw kerb messages and instead wrap them in platform goo like GSS.

There's also the negotiate path, which is subtly different, but still basically the same premise.

In short, the thing you got out of SSPI is what you send to the server. No need to do any additional work, and you can most likely skip over using this library if you want.

________________________________

**Comment by Sentoj** [comment]
Thanks for your reply. What I got from SSPI is only the Kerberos token and not the SPNEGO wrapped AP-REQ. But I am hoping that gets sent automatically during the Http request (after receiving 401 initially). Otherwise, I would have to think about a way to combine SSPI and Kerberos.NET (which exposes AP-REQ).

**Comment by SteveSyfuhs** [comment]
Use "negotiate" instead of kerberos as the call package and SSPI will wrap it in spnego.

________________________________
